### ISSUE TITLE
[Feature request] Separate cold_ and hot_tolerance settings for each mode

### ISSUE THREAD

**Issue by ab0tj** [zacs/ha-dualmodegeneric#10]
I currently use two separate generic_thermostat instances to control a furnace and an evaporative cooler. In order to prevent short cycling on the cooler, I use a fairly high hot_tolerance setting on the thermostat for the cooler. I suspect this would not be a great thing during the winter when the furnace is running. It would be wonderful to have separate settings based on if it is currently heating or cooling.

I'll also look at the code to see if I could just do this and submit a pull request, but Python is not my strong suit. Thanks for all your hard work on this component!

**Comment by KairuByte** [comment]
Are you certain this isn't already possible? The readme claims that all existing options of the generic thermostat integration should work/exist, and separate hot/cold tolerances is one such option.

**Comment by zacs** [comment]
When I put the plugin together I copied the mainline generic_thermostat and
made updates, so yes that should work.
