### ISSUE TITLE
[Feature request] Support setting a unique_id

### ISSUE THREAD

**Issue by Nick-Adams-AU** [zacs/ha-dualmodegeneric#15]
Thanks for your integration!

I would like to be able to specify a unique_id in yaml so that I can assign each climate control to a particular area. Currently, this is not possible due to the entity lacking a unique id:

```This entity ("climate.bed_3") does not have a unique ID, therefore its settings cannot be managed from the UI. See the documentation for more detail.```

**Comment by AWoodley** [comment]
Have created a pull request for this - #26

**Comment by zacs** [comment]
Fixed in #26 -- thanks @AWoodley!
