### ISSUE TITLE
Merge with core?

### ISSUE THREAD

**Issue by mbrevda** [zacs/ha-dualmodegeneric#20]
Was wondering if it would make sense to merge these changes with the generic_theormostat that in core instead of requing HACS?

**Comment by zacs** [comment]
I certainly agree -- although I suppose it would be more of a `template_thermostat` since that is a bit more in line (for naming) with other template devices. But having seen the insane bar for entry into core, I don't think there's much chance that I'm able to spend the time to get that done.

**Comment by mbrevda** [comment]
Oh, didn't realize it was that challenging. If you work up the the courage,
drop a link to the PR here - would love to follow along!

**Comment by zacs** [comment]
Appreciate the support! Unfortunately since HA is used by so many people and in so many different environments, they [rightly] have a pretty high quality bar for getting into the core. Will close this issue for now, thanks!
