### ISSUE TITLE
'CONF_FEELS_LIKE' is not defined

### ISSUE THREAD

**Issue by danps1** [zacs/ha-dualmodegeneric#22]
Hi,

Since updating to version 7670e6c, when attempting to restart HA Core, I get the following failure...

``` Failed to call service homeassistant/restart. name 'CONF_FEELS_LIKE' is not defined ```

I fixed it by commenting out line `107` in `climate.py` like...

```        # vol.Optional(CONF_FEELS_LIKE): cv.boolean,```

Thanks

Dan

**Comment by zacs** [comment]
Thanks much for catching quickly!
