### ISSUE TITLE
Climate heat_cool mode doesn't work, and UI errors from HA 2021.6.1 and up

### ISSUE THREAD

**Issue by DNKROZ** [zacs/ha-dualmodegeneric#25]
Hello.

I'm running HA in a docker container using an nvidia Jetson Nano (arm64 arch).

The new heat & cool mode (nice addition btw) is broken with HA versions **2021.6.1** and above, it does however work using **2021.6.0** version, as a simple downgrade fixes the problem (it resets though heating temp to the max to do so)

When trying to set the climate entity to "heat_cool" a message pops up in the UI:

**"Unsupported operand type(s) for +: 'NoneType' and 'float'"**

And it doesn't work, however this doesn't trigger an error in the custom_components.dualmode_generic.climate log but in the homeassistant.components.websocket_api.http.connection

You can find all the log for that run here (**debug** for custom_components.dualmode_generic.climate **is turned on**) :

https://pastebin.com/X5jScxEj

Also you can find an screenshot for the UI errors here:

https://nextcloud.dnkroz.es/s/GRNqpfxSTKCSoZi/preview

And the messsage here:

https://nextcloud.dnkroz.es/s/mH3SnEw3MZtT8Pn/preview

Best regards.

**Comment by zacs** [comment]
Hmm it looks very similar to #1, which I was not able to repro either. My guess was that it was a race condition (dualmode getting set up before the actual sensors were) and it ended up working after a few seconds. Does your thermostat work at all?

**Comment by DNKROZ** [comment]
I've left them several hours and they don't get to work at all using heat_cool mode, however, they do work if I change the mode to heat or cool, but if I select the heat_cool mode again I get the error.

I think the problem is that it's not restoring previously selected temps and defaulting to the ones stated in the configuration, which I din't have (I relied only on saved values) and thus the empty value. I've entered those in the configuration file and now I don't get the error, however, everytime that I restart HA it doesn't restore the previously saved values and reset the target_low to the one from the configuration file.

**Comment by zacs** [comment]
@DNKROZ can you give it a try now? It may have been fixed by #38.

**Comment by DNKROZ** [comment]
Hi @zacs , I've just tried it with the last hacs commit, it fixes the dual mode heat/cool setup and it works, however, it does so as long as you have target low & high temps stated in the configuration, it doesn't store values from one run to another and if you delete those variables from the config the behaviour stays the same ("Unsupported operand type(s) for +: 'NoneType' and 'float'", etc).

I'm however very pleased to have dual mode working again :), not storing those values is a minor bug for me.

Best regards.
