### ISSUE TITLE
"Precision" feature not working

### ISSUE THREAD

**Issue by dave0111** [zacs/ha-dualmodegeneric#33]
"Precision" feature, natively integrated in generic_thermostat component is not recognized by the custom thermosat: even though it is set to 1.0, i still get steps of 0.5°

**Comment by sebastianeferrer** [comment]
Found the issue we should add target_temperatura_set as generic thermostat does https://github.com/zacs/ha-dualmodegeneric/blob/44b241939627d7eedd7e47de07eac65e2c98056d/custom_components/dualmode_generic/climate.py#L487

**Comment by sebastianeferrer** [comment]
https://github.com/zacs/ha-dualmodegeneric/pull/34

You can get the fix from PR34

**Comment by sebastianeferrer** [comment]
https://github.com/zacs/ha-dualmodegeneric/pull/34 was merged, you can close this issue now.
