### ISSUE TITLE
Cannot go from cooling to heating state

### ISSUE THREAD

**Issue by Frag31337** [zacs/ha-dualmodegeneric#41]
Line 770 need to use this string to avoid this problem
                elif (self._hvac_mode == HVAC_MODE_HEAT_COOL) and (is_comfortable  or (self.hass.states.is_state(self.cooler_entity_id, STATE_ON) and too_cold) or (self.hass.states.is_state(self.heater_entity_id, STATE_ON) and too_hot)):

**Comment by peanutsguy** [comment]
I'm seeing the same problem while using HEAT/COOL (commit 75f6674)

Home Assistant 2023.3.1
Frontend 20230302.0 - latest
