### ISSUE TITLE
Merging two thermostats question

### ISSUE THREAD

**Issue by Vartkat** [zacs/ha-dualmodegeneric#44]
Hello,

I'm looking for a logic solution to the following situation : two real thermostats (Honeywell), one drives an AC, the other a Heating system.
The place is rented and people often ask heat from the AC thermostat (on which there's no heating system connected) or ask cool from the Heating thermostat (on which there's no cooling connected). And sometimes they even ask heat and cool at the same time !

What I'm lloking for is merging the two thermstats, on a visual lovelace basis but more on a logic basis.

I was wondering if the Dual mode thermostat could solve this ?
I understand that I'll have to create template switches for each thermostat :

For the AC switch template (correct me if I'm wrong) the switch should call service climate.turn_on but should it also call climate.set_temperature ? Or Dual mode thermostat will be able to send it's target temp to the right thermostat ?

Tanks for your help

Regards
V.

**Comment by zacs** [comment]
There are a few ways to do this. Probably the simplest would be to have your heater and cooler switch templates not just call the climate.turn_on, but also have a second action that calls climate.set_temperature, where the value you send is just a reference to your dualmode_generic's target temp. 

You'd also want an automation that listened for any changes to the target temp in your gualmode_generic, and called climate.set_temperature on either of the real heater or cooler (depending on which one is currently active).
