### ISSUE TITLE
[Feature request] Show % temperature sensor

### ISSUE THREAD

**Issue by javixuwi** [zacs/ha-dualmodegeneric#46]
It will be interesting to show the battery  % of the temperature sensor.

**Comment by david-kalbermatten** [comment]
You can do that by using a custom thermostat card like this: https://github.com/nervetattoo/simple-thermostat
Adding a battery % to the climate entity is not possible as far as I'm aware and also wouldn't show up in the default thermostat card of Home Assistant Lovelace UI.
