### ISSUE TITLE
Unset 'temperature' attribute when using dual set point.

### ISSUE THREAD

**Issue by arifeinberg** [zacs/ha-dualmodegeneric#48]
Would it be possible to unset the "temperature" attribute when using dual set points?  At present, my thermostat looks like this: 
![image](https://user-images.githubusercontent.com/1208877/167274219-ce252e3d-76db-4945-9e1e-28046a5399f7.png)

Ideally, would not have to deal with temperature attribute when using target_temp_high and target_temp_low.

**Comment by jack3308** [comment]
Did you ever find a solution to this? I'm running into the same issue at the moment. And it's causing the new more-info view to be unusable in heat_cool mode.

**Comment by Excentyl** [comment]
Hi, I have attempted to write a fix for this issue since it causes the tile card and more info popups to be unusable in home assistant 2023.10, as explained above. See pull request #58.

**Comment by Excentyl** [comment]
The pull request has been approved - thanks to Zacs for the fast turnaround. This issue has now been fixed for my entities, so hopefully this has now been fixed for you as well.
