### ISSUE TITLE
Unable to update from sensor: could not convert string to float: 'unknown'

### ISSUE THREAD

**Issue by ciumagcatalin** [zacs/ha-dualmodegeneric#5]
On Home Assistant Core 0.104 I am getting: Unable to update from sensor: could not convert string to float: 'unknown'.
The setup was working fine on the older HA versions and my setup is:

  - platform: dualmode_generic
    name: Small Bedroom Thermostat
    heater: switch.small_bedroom_heating
    cooler: switch.living_air_conditioner
    target_sensor: sensor.small_bedroom_temperature
    min_temp: 18
    max_temp: 30
    away_temp: 20
    initial_hvac_mode: "heat"
    cold_tolerance: 0.3
    hot_tolerance: 0.1
  - platform: dualmode_generic
    name: Kitchen Thermostat
    heater: switch.kitchen_heating
    cooler: switch.living_air_conditioner
    target_sensor: sensor.living_temperature
    min_temp: 18
    max_temp: 30
    away_temp: 20
    initial_hvac_mode: "heat"
    cold_tolerance: 0.3
    hot_tolerance: 0.1

**Comment by ciumagcatalin** [comment]
I think this happen when my homeassistant load first time and the sensors are not populated. I don't get it anymore after some time.

**Comment by zacs** [comment]
Yah, this happens to me as well when the dualmode component gets loaded. I
could potentially add some sort of delay to it, but I assume this happens
with the official generic component as well. I’ll take a look at the latest
code for that component and see if there is delay logic I can borrow.

**Comment by bbbates** [comment]
I suspect this fix (https://github.com/zacs/ha-dualmodegeneric/pull/6/files#diff-f6c9a6f9f4807af09d43c079b5749e5aR214) will solve that issue for you.

**Comment by ciumagcatalin** [comment]
> I suspect this fix (https://github.com/zacs/ha-dualmodegeneric/pull/6/files#diff-f6c9a6f9f4807af09d43c079b5749e5aR214) will solve that issue for you.

But I got the last version 3 days ago. Maybe I missed smth. Is there anything I can help with?

**Comment by bbbates** [comment]
> > I suspect this fix (https://github.com/zacs/ha-dualmodegeneric/pull/6/files#diff-f6c9a6f9f4807af09d43c079b5749e5aR214) will solve that issue for you.
> 
> But I got the last version 3 days ago. Maybe I missed smth. Is there anything I can help with?

I only pushed that PR today and it hasn’t been merged yet 🙂

**Comment by bbbates** [comment]
@zacs merged that potential fix in. @ciumagcatalin Can you give it a test with the latest?

**Comment by ciumagcatalin** [comment]
@bbbates , it works. I just put it today in and I don't get those messages anymore. Thanks!!

**Comment by zacs** [comment]
Thanks @bbbates for the fix! Fixed in 88a4611f517ef36985bcbbadd80904de30009eb5.
