### ISSUE TITLE
Target Temp High and Low no longer adjustable in new 2023.12 Lovelace Thermostat Card

### ISSUE THREAD

**Issue by nox418** [zacs/ha-dualmodegeneric#62]
Hello,
After 2023.12 upgrade low and high target temperatures are no longer visible nor adjustable in the new lovelace thermostat card.
This completely broke my whole climate management logic and I needed to immediatly rolll back.
Are there any chances to get this fixed?
![2023-12-27_11h05_15](https://github.com/zacs/ha-dualmodegeneric/assets/36671684/6020860c-5334-40d3-8f16-3eba6fbb9f47)
![2023-12-27_11h09_51](https://github.com/zacs/ha-dualmodegeneric/assets/36671684/8cf5dcc2-fcd8-49f0-ae30-2cda8cf2ffec)

**Comment by milandzuris** [comment]
after 2024.1 stop working

**Comment by david-kalbermatten** [comment]
Fixed with #65
