### ISSUE TITLE
Addon Using Deprecated Features - Alternative Available

### ISSUE THREAD

**Issue by djripcord** [zacs/ha-dualmodegeneric#63]
This addon is using features in Home Assistant that will be deprecated by 2025.1. It needs updated to use the alternative keys supplied by the Home Assistant Devs.

Specifically, this addon is creating errors in the logs that read:
`Entity None (<class 'custom_components.dualmode_generic.climate.DualModeGenericThermostat'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|TARGET_TEMPERATURE_RANGE: 3>,`

Please see https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation for more information about the features being deprecated.

**Comment by david-kalbermatten** [comment]
Fixed with #65
