### ISSUE TITLE
Add automatic (HVAC_MODE_HEAT_COOL) mode

### ISSUE THREAD

**Issue by zacs** [zacs/ha-dualmodegeneric#9]
According to the new climate entity, [AUTO mode is reserved for a unit operating on its own intelligence](https://developers.home-assistant.io/docs/core/entity/climate) (eg. something AI based), so supporting a temp range (and corresponding heater or cooler turning off) means supporting HVAC_MODE_HEAT_COOL mode.

**Comment by bbbates** [comment]
I suspect this fork might be trying the same thing 🙂

**Comment by zacs** [comment]
Hah! I had not yet seen that. @FPSlacker do feel free to submit a PR for merge into this repo.
